const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Platform,
		C3.Behaviors.Pin,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Behaviors.lunarray_LiteTween.Acts.SetTarget,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Sprite.Acts.MoveAtAngle
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{tanah: 0},
	{Sprite9: 0},
	{Bush: 0},
	{Grass: 0},
	{Grass2: 0},
	{Skeleton: 0},
	{Tree: 0},
	{Stone: 0},
	{Cactus: 0},
	{titikawal: 0},
	{Solid: 0},
	{grid: 0},
	{ctrlleft: 0},
	{ctrlright: 0},
	{ctrljump: 0},
	{Sine: 0},
	{musuh: 0},
	{heart: 0},
	{type: 0},
	{nyawa: 0},
	{lubang: 0},
	{move: 0},
	{Platform: 0},
	{musuh2: 0},
	{Crate: 0},
	{Pin: 0},
	{coin1: 0},
	{coin2: 0},
	{coinangka: 0},
	{LiteTween: 0},
	{pertanyaan1: 0},
	{logopertanyaan: 0},
	{"1a": 0},
	{"1b": 0},
	{"1c": 0},
	{"1d": 0},
	{"1e": 0},
	{menjawabbenar: 0},
	{menjawabsalah: 0},
	{silahkanjawab: 0},
	{nilai: 0},
	{gameover: 0},
	{home: 0},
	{TiledBackground2: 0},
	{bglevelcomplete: 0},
	{tiitkakhir: 0},
	{pijakan2: 0},
	{pijakan3: 0},
	{pijakan4: 0},
	{Keyboard: 0},
	{Touch: 0},
	{bghome: 0},
	{tombolexit: 0},
	{tombolbermain: 0},
	{tombolbelajar: 0},
	{tombolkembali: 0},
	{Browser: 0},
	{Mouse: 0},
	{logopertanyaan2: 0},
	{logopertanyaan3: 0},
	{logopertanyaan4: 0},
	{logopertanyaan5: 0},
	{pertanyaan2: 0},
	{pertanyaan3: 0},
	{pertanyaan4: 0},
	{pertanyaan5: 0},
	{menjawabbenar2: 0},
	{menjawabsalah2: 0},
	{menjawabbenar3: 0},
	{menjawabsalah3: 0},
	{menjawabbenar4: 0},
	{menjawabsalah4: 0},
	{menjawabbenar5: 0},
	{menjawabsalah5: 0},
	{"2a": 0},
	{"2b": 0},
	{"2c": 0},
	{"2d": 0},
	{"2e": 0},
	{"3a": 0},
	{"3b": 0},
	{"3c": 0},
	{"3d": 0},
	{"3e": 0},
	{"4a": 0},
	{"4b": 0},
	{"4c": 0},
	{"4d": 0},
	{"4e": 0},
	{"5a": 0},
	{"5b": 0},
	{"5c": 0},
	{"5d": 0},
	{"5e": 0},
	{silahkanjawab2: 0},
	{silahkanjawab3: 0},
	{silahkanjawab4: 0},
	{silahkanjawab5: 0},
	{Cactus2: 0},
	{Cactus3: 0},
	{Cactus4: 0},
	{Cactus5: 0},
	{pijakan1: 0},
	{pijakan5: 0},
	{Audio: 0},
	{musuhburung2: 0},
	{musuhgear2: 0},
	{musuhgear3: 0},
	{musuhgear4: 0},
	{musuhgear5: 0},
	{musuhgear6: 0},
	{musuhgear7: 0},
	{musuhburung3: 0},
	{popupgameover: 0},
	{popupgamecomplete: 0},
	{DragDrop: 0},
	{materi: 0},
	{ScrollTo: 0},
	{Flash: 0},
	{pemain: 0},
	{musuhlubang1: 0},
	{popupnilaikurang: 0},
	{downloadapk: 0},
	{lihattutor: 0},
	{lihatnilai: 0},
	{Coin: 0},
	{lagugame: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	tanah: class extends self.ITiledBackgroundInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Bush: class extends self.ISpriteInstance {},
	Grass: class extends self.ISpriteInstance {},
	Grass2: class extends self.ISpriteInstance {},
	Skeleton: class extends self.ISpriteInstance {},
	Tree: class extends self.ISpriteInstance {},
	Stone: class extends self.ISpriteInstance {},
	Cactus: class extends self.ISpriteInstance {},
	titikawal: class extends self.ISpriteInstance {},
	grid: class extends self.ITiledBackgroundInstance {},
	ctrlleft: class extends self.ISpriteInstance {},
	ctrlright: class extends self.ISpriteInstance {},
	ctrljump: class extends self.ISpriteInstance {},
	musuh: class extends self.ISpriteInstance {},
	heart: class extends self.ISpriteInstance {},
	nyawa: class extends self.ITextInstance {},
	lubang: class extends self.ITiledBackgroundInstance {},
	musuh2: class extends self.ISpriteInstance {},
	Crate: class extends self.ISpriteInstance {},
	coin1: class extends self.ISpriteInstance {},
	coin2: class extends self.ISpriteInstance {},
	coinangka: class extends self.ITextInstance {},
	pertanyaan1: class extends self.ISpriteInstance {},
	logopertanyaan: class extends self.ISpriteInstance {},
	_1a: class extends self.ITiledBackgroundInstance {},
	_1b: class extends self.ITiledBackgroundInstance {},
	_1c: class extends self.ITiledBackgroundInstance {},
	_1d: class extends self.ITiledBackgroundInstance {},
	_1e: class extends self.ITiledBackgroundInstance {},
	menjawabbenar: class extends self.ISpriteInstance {},
	menjawabsalah: class extends self.ISpriteInstance {},
	silahkanjawab: class extends self.ITextInstance {},
	nilai: class extends self.ITextInstance {},
	gameover: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	bglevelcomplete: class extends self.ISpriteInstance {},
	tiitkakhir: class extends self.ISpriteInstance {},
	pijakan2: class extends self.ISpriteInstance {},
	pijakan3: class extends self.ISpriteInstance {},
	pijakan4: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	bghome: class extends self.ISpriteInstance {},
	tombolexit: class extends self.ISpriteInstance {},
	tombolbermain: class extends self.ISpriteInstance {},
	tombolbelajar: class extends self.ISpriteInstance {},
	tombolkembali: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	logopertanyaan2: class extends self.ISpriteInstance {},
	logopertanyaan3: class extends self.ISpriteInstance {},
	logopertanyaan4: class extends self.ISpriteInstance {},
	logopertanyaan5: class extends self.ISpriteInstance {},
	pertanyaan2: class extends self.ISpriteInstance {},
	pertanyaan3: class extends self.ISpriteInstance {},
	pertanyaan4: class extends self.ISpriteInstance {},
	pertanyaan5: class extends self.ISpriteInstance {},
	menjawabbenar2: class extends self.ISpriteInstance {},
	menjawabsalah2: class extends self.ISpriteInstance {},
	menjawabbenar3: class extends self.ISpriteInstance {},
	menjawabsalah3: class extends self.ISpriteInstance {},
	menjawabbenar4: class extends self.ISpriteInstance {},
	menjawabsalah4: class extends self.ISpriteInstance {},
	menjawabbenar5: class extends self.ISpriteInstance {},
	menjawabsalah5: class extends self.ISpriteInstance {},
	_2a: class extends self.ISpriteInstance {},
	_2b: class extends self.ISpriteInstance {},
	_2c: class extends self.ISpriteInstance {},
	_2d: class extends self.ISpriteInstance {},
	_2e: class extends self.ISpriteInstance {},
	_3a: class extends self.ISpriteInstance {},
	_3b: class extends self.ISpriteInstance {},
	_3c: class extends self.ISpriteInstance {},
	_3d: class extends self.ISpriteInstance {},
	_3e: class extends self.ISpriteInstance {},
	_4a: class extends self.ISpriteInstance {},
	_4b: class extends self.ISpriteInstance {},
	_4c: class extends self.ISpriteInstance {},
	_4d: class extends self.ISpriteInstance {},
	_4e: class extends self.ISpriteInstance {},
	_5a: class extends self.ISpriteInstance {},
	_5b: class extends self.ISpriteInstance {},
	_5c: class extends self.ISpriteInstance {},
	_5d: class extends self.ISpriteInstance {},
	_5e: class extends self.ISpriteInstance {},
	silahkanjawab2: class extends self.ITextInstance {},
	silahkanjawab3: class extends self.ITextInstance {},
	silahkanjawab4: class extends self.ITextInstance {},
	silahkanjawab5: class extends self.ITextInstance {},
	Cactus2: class extends self.ISpriteInstance {},
	Cactus3: class extends self.ISpriteInstance {},
	Cactus4: class extends self.ISpriteInstance {},
	Cactus5: class extends self.ISpriteInstance {},
	pijakan1: class extends self.ISpriteInstance {},
	pijakan5: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	musuhburung2: class extends self.ISpriteInstance {},
	musuhgear2: class extends self.ISpriteInstance {},
	musuhgear3: class extends self.ISpriteInstance {},
	musuhgear4: class extends self.ISpriteInstance {},
	musuhgear5: class extends self.ISpriteInstance {},
	musuhgear6: class extends self.ISpriteInstance {},
	musuhgear7: class extends self.ISpriteInstance {},
	musuhburung3: class extends self.ISpriteInstance {},
	popupgameover: class extends self.ISpriteInstance {},
	popupgamecomplete: class extends self.ISpriteInstance {},
	materi: class extends self.ISpriteInstance {},
	pemain: class extends self.ISpriteInstance {},
	musuhlubang1: class extends self.ISpriteInstance {},
	popupnilaikurang: class extends self.ISpriteInstance {},
	downloadapk: class extends self.ISpriteInstance {},
	lihattutor: class extends self.ISpriteInstance {},
	lihatnilai: class extends self.ISpriteInstance {}
}